version: '3.3'

volumes:
  media:
  static:
  pg_data:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    image: valuas/foodgram-back
    env_file: .env
    command: 
      - python manage.py migrate
      - python manage.py collectstatic
      - cp -r /app/collected_static/. /backend_static/
      - python import_ingredients_to_db.py
    volumes:
      - media:/app/media
      - static:/backend_static
    depends_on: 
      - db
      
  frontend:
    container_name: foodgram-front
    image: valuas/foodgram-front
    env_file: .env
    volumes:
      - static:/frontend_static
      - ../frontend/:/app/result_build/
  
  nginx:
    container_name: foodgram-proxy
    image: valuas/foodgram-proxy 
    env_file: .env
    ports:
      - "7000:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media